[package]
name = "spr"
version = "1.3.0"
authors = ["Sven Over <sven@cord.com>", "Jozef Mokry <jozef@cord.com>"]
description = "Submit pull requests for individual, amendable, rebaseable commits to GitHub"
repository = "https://github.com/getcord/spr"
homepage = "https://github.com/getcord/spr"
license = "MIT"
edition = "2021"
exclude = [".github", ".gitignore"]

[dependencies]
async-compat = "^0.2.1"
async-executor = "^1.4.1"
async-io = "^1.6.0"
async-lock = "^2.4.0"
async-process = "^1.3.0"
clap = { version = "^3.0.14", features = ["derive", "wrap_help"] }
console = "^0.15.0"
dialoguer = "^0.10.1"
futures = "^0.3.21"
futures-lite = "^1.12.0"
git2 = "^0.14.2"
indoc = "^1.0.3"
lazy-regex = "^2.2.2"
octocrab = "^0.16.0"
serde = "^1.0.136"
textwrap = "0.15.0"
thiserror = "^1.0.30"
unicode-normalization = "^0.1.19"
graphql_client = { git = "https://github.com/graphql-rust/graphql-client", rev = "64ad4e34a6f9eb120ea83934bd68af18dbaf4a15" }
reqwest = { version = "^0.11", features = ["json"] }

[dev-dependencies]
smol = "^1.2.5"
