name: Build and deploy spr documentation

concurrency:
  group: gh-pages

on:
  push:
    branches:
      - master
    paths:
      - "book.toml"
      - "docs/**"

jobs:
  mdbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Install mdbook-mermaid
        uses: actions-rs/install@v0.1
        with:
          crate: mdbook-mermaid
          version: "latest"

      - name: Run mdBook
        run: |
          mdbook-mermaid install
          mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          publish_branch: gh-pages
